[build]
  command = "bun run db:generate && bun run build"
[build.environment]
  NODE_VERSION = "20"
  BUN_VERSION = "latest"
  SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_SUPABASE_ANON_KEY,NEXT_PUBLIC_SUPABASE_URL"


